apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flyteagent.name" . }}
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
{{- with .Values.agentSecret.secretData -}}
{{ tpl (toYaml .) $ | nindent 0 }}
{{- end }}
