project_name: flyte
builds:
  - skip: true
release:
  github:
    owner: flyteorg
    name: flyte
  draft: false
  prerelease: auto
  discussion_category_name: General
  name_template: "Flyte v{{.Version}} milestone release"
  disable: false
  extra_files:
    - glob: ./release/*
git:
  ignore_tags:
    - "datacatalog/*"
    - "flyteadmin/*"
    - "flytecopilot/*"
    - "flyteidl/*"
    - "flyteplugins/*"
    - "flytepropeller/*"
    - "flytestdlib/*"
