{{- if .Values.sandbox.buildkit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}-buildkit
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "flyte-sandbox.buildkitSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-sandbox.buildkitSelectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: buildkit
          {{- with .Values.sandbox.buildkit.image }}
          image: {{ printf "%s:%s" .repository .tag | quote }}
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:30003
          ports:
            - name: tcp
              containerPort: 30003
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
{{- end }}
