name: Build & Push All Components Images

on:
  workflow_call:
    inputs:
      version:
        description: "Version of image"
        required: false
        type: string
        default: ci-checks
      push:
        description: "Push to registry"
        required: true
        type: boolean
    secrets:
      FLYTE_BOT_USERNAME:
        required: true
      FLYTE_BOT_PAT:
        required: true

jobs:
  push_docker_image:
    name: Build & Push Image
    strategy:
      fail-fast: false
      matrix:
        component:
          - datacatalog
          - flyteadmin
          - flytecopilot
          - flytepropeller
          - flytescheduler
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ inputs.version }}
      component: ${{ matrix.component }}
      dockerfile: Dockerfile.${{ matrix.component }}
      push: ${{ inputs.push }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}
