name: Mark stale issues

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    name: Close stale issues
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          Hello 👋, this issue has been inactive for over 9 months. To help maintain a clean and focused backlog, 
          we'll be marking this issue as stale and will engage on it to decide if it is still applicable. 

          Thank you for your contribution and understanding! 🙏
        stale-issue-label: "stale"
        exempt-issue-labels: "needs discussion,untriaged"  # Comma-separated list of labels.
        days-before-stale: 270
        days-before-close: -1
        ascending: true # https://github.com/actions/stale#ascending
        operations-per-run: 500
